apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgAbJRW/6Ob4UXJ9ZhQ6/xvyHTi/ujkuPLVziDXubyHLSfUe4dyTz5lWsXdbk6J7ExpURj3aYgrJydqoBtewuq/C5fK2EXlY+/180a2dESAveUeVqeNrKvcTadN6PdjqlIIzD0mdhD/Q3xztQMqf0pXDMXy6WjKoP2lqwQlL4NYBYYrAnR6wD/Jpv14LaQ/jp2BQfZvW/gL3qmxFuDeK0ZKfPrhYvWhtG7MM0PB7qjZMso7bAKjB84Ts2myDLHbyvwH/37K/PRoQlwymsnBoyMUJPhc1WQnvD8wtWw/pZPMcIV/YXEpBihFqPBIt2Oj43sQa412FNsIY/j2OWtbYY1gT6mEVqYDvviw1CWslkEu6x4ObKLSP63SlTpmfoSM19JFU0Kh3DGJpvPZO1l+bOp2upq5hAg3IunC8GWCZO3zNaFdqEh80rHuUBXKE2f3Wdy/2yCMFU8knz22EmaIHUo9YRrO+fOvITxkpkU/E2GKWPsVZkDtX+aOdjXwC8rxenL8I8r6gM2UFIQoEqfkHmuvbHB6Nl0agMX4lWdR6q4Rdv2Ac/rYqbkB4h3r8hGEtpOKq/eNFWURofvmKnOt7JZ0hQv6aHgedjIZKIIzCEYKnJ+oLmsA5++kfOElG1KJeD6TZ+QJr0Jk9Fa0VIMGlqtnLVMzHmOPCFeN6nLfOnXfDQZIMTbt90tBNkeMyrHuhehnhfyMBD4RnbKwsooy0hxytLunMjFacAFe2mf9ZL/XIxOio0jr1byePtw==
  template:
    metadata:
      creationTimestamp: null
      name: image-creds
      namespace: dev
status: {}

